// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwpfumpmicczqwnynagn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3cGZ1bXBtaWNjenF3bnluYWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyODYzNDQsImV4cCI6MjA3NDg2MjM0NH0.DwP0aCkqgSYncigEUeyus7K3EhnWIL6Vjhe_Ig0_V0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});